# Generated by Django 4.2.7 on 2025-07-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riderpages', '0003_ride_driver_ride_transaction_id_alter_ride_status_and_more'),
        ('driverpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='ride',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riderpages.ride'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riderpages.ride'),
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
