# Generated by Django 4.2.7 on 2025-07-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderpages', '0003_ride_driver_ride_transaction_id_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CASH', 'Cash')], max_length=20, null=True),
        ),
    ]
